### PR TITLE
Greedy Algorithm/Activity Selection Problem

### PR DESCRIPTION
**Pull request by cdeepanshu**

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
file not correct
should be 
Greedy/Activity Selection Problem/{ur file .cpp}

**Comment by matthewsamuel95** [comment]
please check again

**Comment by matthewsamuel95** [comment]
please use other code in the repo as an example

**Comment by cdeepanshu** [comment]
is there any error in it

**Comment by matthewsamuel95** [comment]
Yes look at how greedy algos have been placed

**Comment by cdeepanshu** [comment]
ok I will go through it and then submit a new example

**Pull request closed without merging**
