### PR TITLE
How to make a pull request

### PR DESCRIPTION
**Pull request by ShobhitBehl**
Added the file contributing.md on how to make a pull request

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
Collab with https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/pull/297

**Comment by ShobhitBehl** [comment]
Also added a greedy problem solution

**Comment by matthewsamuel95** [comment]
nice add to contributing.md or remove as https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/pull/209 is being worked on

**Comment by ShobhitBehl** [comment]
I'll remove contributing.md

**Comment by ShobhitBehl** [comment]
I can add more greedy problems?
I have a lot.

**Pull request merged**
