### PR TITLE
Created Sack

### PR DESCRIPTION
**Pull request by ThiagoWhispher**

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
What does sack solve

**Comment by ThiagoWhispher** [comment]
The Sack algorithm allows responding offline queries related to node subtree information in a tree.

**Comment by matthewsamuel95** [comment]
write a small readme as this can be cool knowledge for others

**Comment by ThiagoWhispher** [comment]
Done

**Comment by matthewsamuel95** [comment]
@ThiagoWhispher ur readme.md has a link that requires a password plz fix

**Pull request merged**
