### PR TITLE
power_of_x.cpp: Added file for pow or x

### PR DESCRIPTION
**Pull request by mouri11**

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
Infinite loop on negative exponents

**Comment by mouri11** [comment]
Just change the n >> 1 to n / 2. It will take me some time to commit this.

**Comment by matthewsamuel95** [comment]
No the entire algo can be done without loop

**Comment by mouri11** [comment]
You mean to say without recursion?

**Comment by matthewsamuel95** [comment]
For next power of two problem.

**Comment by mouri11** [comment]
Oh. This one is for the pow(x,n) problem. Did I get the issue no. wrong?

**Comment by matthewsamuel95** [comment]
My mistake then. Maybe if n is negative it produces incorrect values.

**Comment by mouri11** [comment]
Yes. For that, just change the part where I wrote n >> 1, to n / 2. Bit manipulation for negative numbers is going wrong.

**Comment by matthewsamuel95** [comment]
Not bit manipulation needed my mistake.

**Comment by mouri11** [comment]
Ok.

**Comment by matthewsamuel95** [comment]
Still incorrect for negative exponents

**Pull request closed without merging**
