### PR TITLE
Power function is implemented in cpp

### PR DESCRIPTION
**Pull request by codeShaurya**
Issue #236 
The power function is implemented in cpp without the library function with clean coding...

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
What if n is divisible by 2 and also negative?

**Comment by codeShaurya** [comment]
I gave input  n =  -4 and p = 3
and the output is -64 which is correct.
Can you give the test cases ??

**Comment by matthewsamuel95** [comment]
My mistake ur correct, great job.

**Comment by codeShaurya** [comment]
Thanks, @matthewsamuel95 :smile:

**Pull request merged**
