### PR TITLE
Adding .gitignore file.

### PR DESCRIPTION
**Pull request by dreamerHarshit**
following files will be ignored -
*.DS_Store
*.pyc
*.txt
.cache/*
*.DS
.idea/*
*.out

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
place code in Data Structures

**Comment by dreamerHarshit** [comment]
done

**Comment by matthewsamuel95** [comment]
not quite correct still please confirm folder is still Math

**Comment by dreamerHarshit** [comment]
> not quite correct still please confirm folder is still Math

do i need to put .gitignore file in DS Folder as well? @matthewsamuel95

**Comment by dreamerHarshit** [comment]
@matthewsamuel95  why this branch is closed, i guess we all can collaborate here in this file only.

**Comment by matthewsamuel95** [comment]
please check https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/issues/301

**Pull request closed without merging**
