### PR TITLE
Added .pyc and .out files to gitignore

### LINKED ISSUE #275: Make a .gitignore
please write a gitignore that at least considers for .pyc and a.out and others

### PR DESCRIPTION
**Pull request by RCMainak**
Fixes #275

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
change out -> a.out*

**Comment by RCMainak** [comment]
Hello @matthewsamuel95, I don't understand what you mean by that. I added *.out in gitignore to ignore any files having `.out` extension. I may have misunderstood the issue. Please clarify what needs to be done.

**Comment by RCMainak** [comment]
Hey @matthewsamuel95 I know how gitignore works, can you clarify what do you want in this specific case. Do you want to ignore all of the files having `.out` extension or do you want to only ignore `a.out` files? 

I would recommend you have all the files with `.out` extensions ignored. Waiting for your response.

**Comment by matthewsamuel95** [comment]
both , plz collab with others as 3 people have similar ideas

**Pull request closed without merging**
