### PR TITLE
Hashing problem

### PR DESCRIPTION
**Pull request by shivanand217**
Added a new problem in the Hashing Type. Check if one array is subset of another or not.

### CODE REVIEW

**Comment by shivanand217** [comment]
Hey hi @matthewsamuel95,

I respect your decision, but can you tell me the reason for closing the pull request.

Thanks.

**Comment by matthewsamuel95** [comment]
the only description I can get from the file is find_whether_an_array_is_subset_of_another_array_set , please add a readme and add to table of contents

**Comment by shivanand217** [comment]
Hey @matthewsamuel95,

Really sorry for the disrespect of the contribution guidelines. I will make make the change.

Thanks.

**Comment by shivanand217** [comment]
@matthewsamuel95 
Sorry to ask but can i add a readme to the solution folder or just add the problem to the Table of contents.

**Pull request closed without merging**
