### PR TITLE
CoinChangeProblem added to DP

### PR DESCRIPTION
**Pull request by shalithasuranga**
This refers to #20

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
try these https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/issues/20

**Comment by shalithasuranga** [comment]
Hello.. @matthewsamuel95  Thanks for the approval. What I can do..

1) Change the code and make PR
2) Create another folder 'Coin Change Problem ( Min Coins)' and add both codes

Thanks

**Comment by matthewsamuel95** [comment]
Add both codes.

**Comment by shalithasuranga** [comment]
Okay.. I do thanks

**Pull request merged**
