### PR TITLE
Fixed issue #150

### PR DESCRIPTION
**Pull request by icy-meteor**
cd to Math/SquareRoot and you can find the C++ algorithm implementation for the same.

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
Please place in Math subfolder

**Comment by matthewsamuel95** [comment]
Your logic is not correct. Please view sample test output below.

Input:
2147395600
Your Output:
289398
Expected:
46340

**Comment by icy-meteor** [comment]
Okay, on it.

**Comment by icy-meteor** [comment]
Fixed, check now.

**Comment by matthewsamuel95** [comment]
Input:
2147395599
Your Output:
46340
Expected:
46339

**Pull request closed without merging**
