### PR TITLE
Program to implement queue using stack.

### PR DESCRIPTION
**Pull request by dreamerHarshit**

### CODE REVIEW

**Comment by matthewsamuel95** [comment]
code in DS

**Comment by dreamerHarshit** [comment]
@matthewsamuel95  i have moved code under DS now. Can you pls check it again.

**Comment by matthewsamuel95** [comment]
DS/Stack/{ur file} follow the file structure that is in placed

**Comment by matthewsamuel95** [comment]
ACM-ICPC-Algorithms/Data Structures/Stack/Implement Stack Using Queues/

same for the other

**Comment by matthewsamuel95** [comment]
remove empty files

**Comment by dreamerHarshit** [comment]
done

**Comment by matthewsamuel95** [comment]
you had an empty file and the file stack_using_queue.cpp was good but was in Data Structures without a space , plz be careful when following instructions

**Pull request merged**
